name: build_job

author: "LamaDai"
description: "Calling Me to Build"

runs:
  using: 'composite'
  steps:
    - run: echo "Git Clone"
      shell: bash 
    - run: echo "Composer Build"
      shell: bash 
    - run: echo "Yarn Build"
      shell: bash 
    - run: echo "Nginx Container Build"
      shell: bash 
    - run: echo "PHP-FPM Container Build"
      shell: bash 
    - run: echo "Docker-compose up"
      shell: bash 
    - run: echo "PHP Migrate DB"
      shell: bash 
    - run: ls -lR
      shell: bash
    - run: |
          cd grc
      shell: bash
    - run: pwd && ls
      shell: bash
    

